// <auto-generated />
namespace TelephoneBook.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class entitiesAddedAndRelations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entitiesAddedAndRelations));
        
        string IMigrationMetadata.Id
        {
            get { return "202001261903369_entitiesAddedAndRelations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
